### ISSUE TITLE
Where can find monero-wallet-cli command line tool?

### ISSUE THREAD

**Issue by scars1** [ZephyrProtocol/zephyr#25]
Prove to someone that you have sent them Zephyr in this transaction
Tx private key can be obtained using get_tx_key command in monero-wallet-cli command line tool
Note: address/subaddress and tx private key are sent to the server, as the calculations are done on the server side

I want check my send,Where can get this cli?

**Comment by laoxu2021** [comment]
同样的问题 ，没人回答吗？

**Comment by ZephyrProtocol** [comment]
Old issue due to support via an exchange that needed to rescan their exchange wallet to see missing user funds.

zephyr-wallet-cli is a cli tool and can we downloaded in releases.
note: you can't retroactively prove sending from the gui wallet by opening it in the cli tool. That info is saved only from sending via the cli tool in the wallet cache file
